-- Menghapus tabel lama jika ada untuk menghindari error saat eksekusi ulang
-- DROP TABLE IF EXISTS public.socialization CASCADE;
-- DROP TABLE IF EXISTS public.notifications CASCADE;
-- DROP TABLE IF EXISTS public.evidence CASCADE;
-- DROP TABLE IF EXISTS public.reports CASCADE;
-- DROP TABLE IF EXISTS public.profiles CASCADE;
-- DROP TYPE IF EXISTS public.user_role CASCADE;
-- DROP TYPE IF EXISTS public.report_status CASCADE;

-- 1. MEMBUAT CUSTOM TYPES UNTUK KONSISTENSI DATA
-- Menggunakan ENUM lebih baik daripada TEXT biasa untuk mencegah kesalahan input.

CREATE TYPE public.user_role AS ENUM (
  'siswa',
  'guru',
  'tppk'
);

CREATE TYPE public.report_status AS ENUM (
  'baru',
  'diproses',
  'selesai',
  'ditolak'
);


-- 2. MEMBUAT TABEL 'PROFILES'
-- Tabel ini adalah perpanjangan dari tabel 'auth.users' milik Supabase.
-- Ini adalah cara standar untuk menyimpan data profil publik yang aman.

CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  role user_role NOT NULL DEFAULT 'siswa',
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.profiles IS 'Menyimpan data profil publik untuk setiap pengguna.';
COMMENT ON COLUMN public.profiles.id IS 'Kunci utama, terhubung langsung ke auth.users.id.';


-- 3. MEMBUAT TABEL 'REPORTS' (LAPORAN)
-- Tabel inti untuk menyimpan semua laporan kekerasan yang masuk.

CREATE TABLE public.reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  description text NOT NULL CHECK (char_length(description) > 10),
  status report_status NOT NULL DEFAULT 'baru',
  is_anonymous boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.reports IS 'Menyimpan semua data laporan bullying.';
COMMENT ON COLUMN public.reports.reporter_id IS 'ID pelapor. Bisa NULL jika laporan bersifat anonim atau user dihapus.';


-- 4. MEMBUAT TABEL 'EVIDENCE' (BUKTI)
-- Tabel untuk menyimpan link ke file-file bukti yang terkait dengan sebuah laporan.

CREATE TABLE public.evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id bigint NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  file_url text NOT NULL,
  file_type text, -- contoh: 'image/jpeg', 'video/mp4'
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.evidence IS 'Menyimpan URL bukti yang terhubung ke satu laporan.';
COMMENT ON COLUMN public.evidence.report_id IS 'Menghubungkan bukti ini ke laporan spesifik di tabel reports.';


-- 5. MEMBUAT TABEL 'NOTIFICATIONS'
-- Menyimpan FCM token untuk keperluan push notification per pengguna.

CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  fcm_token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.notifications IS 'Menyimpan token FCM perangkat pengguna untuk push notifications.';


-- 6. MEMBUAT TABEL 'SOCIALIZATION' (SOSIALISASI & EDUKASI)
-- Menyimpan konten edukasi yang dibuat oleh tim TPPK.

CREATE TABLE public.socialization (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  content text NOT NULL,
  published_at timestamptz DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.socialization IS 'Menyimpan konten sosialisasi dan edukasi dari TPPK.';

-- =================================================================
-- SELESAI
-- =================================================================