CREATE TABLE public.kelas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Kolom untuk tingkat kelas (misal: 1, 2, 3, 4, 5, 6)
  tingkat INT NOT NULL,
  
  -- Kolom untuk nama jurusan/paralel (misal: 'A', 'B', 'C')
  jurusan TEXT NOT NULL,
  
  -- Kolom ini tetap sama, menunjuk ke ID guru yang menjadi wali kelas.
  wali_kelas_id UUID REFERENCES public.profiles(id),
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  -- Memastikan tidak ada kombinasi tingkat dan jurusan yang sama (tidak boleh ada dua kelas '6A')
  CONSTRAINT kelas_tingkat_jurusan_key UNIQUE(tingkat, jurusan)
);

COMMENT ON TABLE public.kelas IS 'Menyimpan data master untuk setiap kelas di sekolah.';
COMMENT ON COLUMN public.kelas.wali_kelas_id IS 'ID dari user (guru) yang menjadi wali kelas.';

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS kelas_id BIGINT REFERENCES public.kelas(id);
COMMENT ON COLUMN public.profiles.kelas_id IS 'ID kelas tempat siswa terdaftar.';