-- Membuat tipe data baru untuk tahapan penanganan
CREATE TYPE public.tahapan_enum AS ENUM ('verifikasi', 'mediasi', 'rehabilitasi', 'lainnya');

-- Membuat tabel untuk menyimpan log/catatan penanganan
CREATE TABLE public.log_penanganan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES public.reports(id),
  author_id UUID NOT NULL REFERENCES public.profiles(id),
  catatan TEXT NOT NULL,
  tahapan tahapan_enum NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.log_penanganan IS 'Menyimpan riwayat catatan/tindakan yang dilakukan admin untuk setiap laporan.';