-- Tabel untuk menyimpan balasan/feedback dari TPPK ke siswa
CREATE TABLE public.balasan_laporan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES public.reports(id),
  author_id UUID NOT NULL REFERENCES public.profiles(id),
  pesan TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Aktifkan RLS
ALTER TABLE public.balasan_laporan ENABLE ROW LEVEL SECURITY;

-- Buat Policies
-- Hanya TPPK yang bisa membuat balasan
CREATE POLICY "Allow TPPK to create replies"
ON public.balasan_laporan FOR INSERT
TO authenticated
WITH CHECK (get_my_role() = 'tppk');

-- Siswa bisa melihat balasan HANYA untuk laporannya sendiri
CREATE POLICY "Allow reporter to view their replies"
ON public.balasan_laporan FOR SELECT
TO authenticated
USING (
  (SELECT reporter_id FROM public.reports WHERE id = report_id) = auth.uid()
);

-- TPPK bisa melihat semua balasan
CREATE POLICY "Allow TPPK to view all replies"
ON public.balasan_laporan FOR SELECT
TO authenticated
USING (get_my_role() = 'tppk');