-- =================================================================
-- FITUR MADING KELAS
-- Fitur untuk siswa berbagi cerita di kelas masing-masing
-- =================================================================

-- 1. TABEL CERITA KELAS
-- Menyimpan cerita yang dibuat oleh siswa untuk kelas mereka
CREATE TABLE public.cerita_kelas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Author cerita (siswa atau admin)
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  
  -- Kelas tempat cerita ini dipublish
  kelas_id BIGINT NOT NULL REFERENCES public.kelas(id) ON DELETE CASCADE,
  
  -- Konten cerita
  judul TEXT NOT NULL CHECK (char_length(judul) >= 3 AND char_length(judul) <= 200),
  konten TEXT NOT NULL CHECK (char_length(konten) >= 10),
  
  -- Gambar pendukung (opsional)
  gambar_url TEXT,
  
  -- Status publikasi
  is_published BOOLEAN NOT NULL DEFAULT true,
  
  -- Timestamp
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.cerita_kelas IS 'Menyimpan cerita yang dibagikan siswa di mading kelas';
COMMENT ON COLUMN public.cerita_kelas.author_id IS 'ID siswa atau admin yang membuat cerita';
COMMENT ON COLUMN public.cerita_kelas.kelas_id IS 'ID kelas tempat cerita dipublish';

-- 2. TABEL TANGGAPAN CERITA
-- Menyimpan komentar/tanggapan dari siswa lain dan guru terhadap cerita
CREATE TABLE public.tanggapan_cerita (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Cerita yang ditanggapi
  cerita_id BIGINT NOT NULL REFERENCES public.cerita_kelas(id) ON DELETE CASCADE,
  
  -- Pemberi tanggapan (siswa, guru, atau admin)
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  
  -- Isi tanggapan
  tanggapan TEXT NOT NULL CHECK (char_length(tanggapan) >= 1 AND char_length(tanggapan) <= 1000),
  
  -- Timestamp
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.tanggapan_cerita IS 'Menyimpan tanggapan/komentar terhadap cerita kelas';
COMMENT ON COLUMN public.tanggapan_cerita.cerita_id IS 'ID cerita yang ditanggapi';
COMMENT ON COLUMN public.tanggapan_cerita.author_id IS 'ID user yang memberikan tanggapan';

-- 3. TRIGGER UNTUK AUTO-UPDATE updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger untuk cerita_kelas
CREATE TRIGGER update_cerita_kelas_updated_at 
    BEFORE UPDATE ON public.cerita_kelas 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger untuk tanggapan_cerita
CREATE TRIGGER update_tanggapan_cerita_updated_at 
    BEFORE UPDATE ON public.tanggapan_cerita 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- 4. INDEX UNTUK PERFORMA
CREATE INDEX idx_cerita_kelas_kelas_id ON public.cerita_kelas(kelas_id);
CREATE INDEX idx_cerita_kelas_author_id ON public.cerita_kelas(author_id);
CREATE INDEX idx_cerita_kelas_created_at ON public.cerita_kelas(created_at DESC);

CREATE INDEX idx_tanggapan_cerita_cerita_id ON public.tanggapan_cerita(cerita_id);
CREATE INDEX idx_tanggapan_cerita_author_id ON public.tanggapan_cerita(author_id);
CREATE INDEX idx_tanggapan_cerita_created_at ON public.tanggapan_cerita(created_at DESC);

-- =================================================================
-- RLS POLICIES UNTUK KEAMANAN
-- =================================================================

-- Enable RLS
ALTER TABLE public.cerita_kelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tanggapan_cerita ENABLE ROW LEVEL SECURITY;

-- POLICIES UNTUK CERITA KELAS

-- 1. Siswa hanya bisa melihat cerita di kelas mereka sendiri
-- 2. Guru hanya bisa melihat cerita di kelas yang mereka wali
-- 3. Admin bisa melihat semua cerita
CREATE POLICY "Users can view stories in their class" ON public.cerita_kelas
    FOR SELECT USING (
        -- Admin bisa lihat semua
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        OR
        -- Siswa bisa lihat cerita di kelas mereka
        (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
            AND kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
        )
        OR
        -- Guru bisa lihat cerita di kelas yang mereka wali
        (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'guru'
            AND kelas_id IN (SELECT id FROM public.kelas WHERE wali_kelas_id = auth.uid())
        )
    );

-- Hanya siswa dan admin yang bisa membuat cerita
CREATE POLICY "Students and admins can create stories" ON public.cerita_kelas
    FOR INSERT WITH CHECK (
        author_id = auth.uid()
        AND (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
            OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        )
        AND (
            -- Siswa hanya bisa posting di kelas mereka sendiri
            (
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
                AND kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
            )
            OR
            -- Admin bisa posting di kelas manapun
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        )
    );

-- Hanya author dan admin yang bisa update/delete cerita
CREATE POLICY "Authors and admins can update their stories" ON public.cerita_kelas
    FOR UPDATE USING (
        author_id = auth.uid()
        OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
    );

CREATE POLICY "Authors and admins can delete their stories" ON public.cerita_kelas
    FOR DELETE USING (
        author_id = auth.uid()
        OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
    );

-- POLICIES UNTUK TANGGAPAN CERITA

-- Bisa melihat tanggapan jika bisa melihat ceritanya
CREATE POLICY "Users can view responses if they can view the story" ON public.tanggapan_cerita
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.cerita_kelas 
            WHERE id = cerita_id
            AND (
                -- Admin bisa lihat semua
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
                OR
                -- Siswa bisa lihat tanggapan cerita di kelas mereka
                (
                    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
                    AND kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
                )
                OR
                -- Guru bisa lihat tanggapan cerita di kelas yang mereka wali
                (
                    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'guru'
                    AND kelas_id IN (SELECT id FROM public.kelas WHERE wali_kelas_id = auth.uid())
                )
            )
        )
    );

-- Semua user bisa memberikan tanggapan jika mereka bisa melihat ceritanya
CREATE POLICY "Users can create responses if they can view the story" ON public.tanggapan_cerita
    FOR INSERT WITH CHECK (
        author_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.cerita_kelas 
            WHERE id = cerita_id
            AND (
                -- Admin bisa tanggapi semua
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
                OR
                -- Siswa bisa tanggapi cerita di kelas mereka
                (
                    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
                    AND kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
                )
                OR
                -- Guru bisa tanggapi cerita di kelas yang mereka wali
                (
                    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'guru'
                    AND kelas_id IN (SELECT id FROM public.kelas WHERE wali_kelas_id = auth.uid())
                )
            )
        )
    );

-- Hanya author dan admin yang bisa update/delete tanggapan
CREATE POLICY "Authors and admins can update their responses" ON public.tanggapan_cerita
    FOR UPDATE USING (
        author_id = auth.uid()
        OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
    );

CREATE POLICY "Authors and admins can delete their responses" ON public.tanggapan_cerita
    FOR DELETE USING (
        author_id = auth.uid()
        OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
    );

-- =================================================================
-- SELESAI - MADING KELAS
-- ================================================================= 