-- =================================================================
-- BERANI BICARA - COMPLETE DATABASE INITIALIZATION SCRIPT
-- Anti-Bullying Application Database Schema
-- 
-- This script consolidates all database migrations, RLS policies,
-- functions, triggers, and seed data into a single initialization file.
-- 
-- Created: October 2025
-- =================================================================

-- =================================================================
-- 1. ENABLE REQUIRED EXTENSIONS
-- =================================================================

-- Enable pg_net extension for HTTP calls (webhooks)
CREATE EXTENSION IF NOT EXISTS pg_net;

-- =================================================================
-- 2. DROP EXISTING OBJECTS (FOR CLEAN REINSTALL)
-- =================================================================

-- Drop triggers first
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP TRIGGER IF EXISTS on_report_created ON public.reports;
DROP TRIGGER IF EXISTS on_reply_created ON public.balasan_laporan;
DROP TRIGGER IF EXISTS update_cerita_kelas_updated_at ON public.cerita_kelas;
DROP TRIGGER IF EXISTS update_tanggapan_cerita_updated_at ON public.tanggapan_cerita;

-- Drop functions
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.get_my_role() CASCADE;
DROP FUNCTION IF EXISTS public.get_report_status_counts() CASCADE;
DROP FUNCTION IF EXISTS public.create_new_report(TEXT, TEXT, BOOLEAN, TEXT[]) CASCADE;
DROP FUNCTION IF EXISTS public.notify_new_report() CASCADE;
DROP FUNCTION IF EXISTS public.notify_new_reply() CASCADE;
DROP FUNCTION IF EXISTS public.notify_new_report_v2() CASCADE;
DROP FUNCTION IF EXISTS public.notify_new_reply_v2() CASCADE;
DROP FUNCTION IF EXISTS public.update_updated_at_column() CASCADE;

-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS public.tanggapan_cerita CASCADE;
DROP TABLE IF EXISTS public.cerita_kelas CASCADE;
DROP TABLE IF EXISTS public.balasan_laporan CASCADE;
DROP TABLE IF EXISTS public.log_penanganan CASCADE;
DROP TABLE IF EXISTS public.evidence CASCADE;
DROP TABLE IF EXISTS public.reports CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.socialization CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.kelas CASCADE;

-- Drop custom types
DROP TYPE IF EXISTS public.user_role CASCADE;
DROP TYPE IF EXISTS public.report_status CASCADE;
DROP TYPE IF EXISTS public.tahapan_enum CASCADE;

-- =================================================================
-- 3. CREATE CUSTOM TYPES
-- =================================================================

-- User roles in the system
CREATE TYPE public.user_role AS ENUM (
  'siswa',    -- Student
  'guru',     -- Teacher
  'tppk'      -- Admin (Tim Pencegahan dan Penanganan Kekerasan)
);

-- Report status progression
CREATE TYPE public.report_status AS ENUM (
  'baru',     -- New report
  'diproses', -- Being processed
  'selesai',  -- Completed
  'ditolak'   -- Rejected
);

-- Handling stages for admin logs
CREATE TYPE public.tahapan_enum AS ENUM (
  'verifikasi',   -- Verification
  'mediasi',      -- Mediation
  'rehabilitasi', -- Rehabilitation
  'lainnya'       -- Other
);

-- =================================================================
-- 4. CREATE CORE TABLES
-- =================================================================

-- 4.1 CLASSES TABLE
-- Master data for school classes
CREATE TABLE public.kelas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tingkat INT NOT NULL,                                    -- Grade level (1-6)
  jurusan TEXT NOT NULL,                                   -- Class section (A, B, C, etc.)
  wali_kelas_id UUID REFERENCES auth.users(id),           -- Homeroom teacher ID
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  -- Ensure unique combination of grade and section
  CONSTRAINT kelas_tingkat_jurusan_key UNIQUE(tingkat, jurusan)
);

COMMENT ON TABLE public.kelas IS 'Master data for school classes';
COMMENT ON COLUMN public.kelas.wali_kelas_id IS 'ID of the homeroom teacher';

-- 4.2 USER PROFILES TABLE
-- Extended user information linked to auth.users
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  role user_role NOT NULL DEFAULT 'siswa',
  kelas_id BIGINT REFERENCES public.kelas(id),            -- Student's class
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.profiles IS 'Extended user profile information';
COMMENT ON COLUMN public.profiles.id IS 'Primary key linked to auth.users.id';
COMMENT ON COLUMN public.profiles.kelas_id IS 'Class ID where student is enrolled';

-- 4.3 REPORTS TABLE
-- Core table for bullying reports
CREATE TABLE public.reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title TEXT,                                              -- Report title
  description text NOT NULL CHECK (char_length(description) > 10),
  status report_status NOT NULL DEFAULT 'baru',
  is_anonymous boolean NOT NULL DEFAULT false,             -- Semi-anonymous flag
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.reports IS 'Bullying reports submitted by users';
COMMENT ON COLUMN public.reports.reporter_id IS 'Reporter ID (can be NULL for anonymous reports)';
COMMENT ON COLUMN public.reports.title IS 'Short title for the report';
COMMENT ON COLUMN public.reports.is_anonymous IS 'Flag for semi-anonymous reports (name hidden from UI)';

-- 4.4 EVIDENCE TABLE
-- File attachments for reports
CREATE TABLE public.evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id bigint NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  file_url text NOT NULL,
  file_type text,                                          -- MIME type
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.evidence IS 'Evidence files attached to reports';
COMMENT ON COLUMN public.evidence.report_id IS 'Links evidence to specific report';

-- 4.5 HANDLING LOGS TABLE
-- Admin action logs for report processing
CREATE TABLE public.log_penanganan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES public.reports(id),
  author_id UUID NOT NULL REFERENCES public.profiles(id),
  catatan TEXT NOT NULL,                                   -- Action notes
  tahapan tahapan_enum NOT NULL,                          -- Handling stage
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.log_penanganan IS 'Admin action logs for report handling';

-- 4.6 REPORT REPLIES TABLE
-- Admin responses to students
CREATE TABLE public.balasan_laporan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES public.reports(id),
  author_id UUID NOT NULL REFERENCES public.profiles(id),
  pesan TEXT NOT NULL,                                     -- Reply message
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.balasan_laporan IS 'Admin replies to student reports';

-- 4.7 SOCIALIZATION CONTENT TABLE
-- Educational content from admin
CREATE TABLE public.socialization (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  content text NOT NULL,
  cover_image_url TEXT,                                    -- Cover image URL
  published_at timestamptz DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.socialization IS 'Educational content from TPPK team';
COMMENT ON COLUMN public.socialization.cover_image_url IS 'URL to cover image for educational article';

-- 4.8 CLASS STORIES TABLE
-- Student stories shared in class bulletin board
CREATE TABLE public.cerita_kelas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  kelas_id BIGINT NOT NULL REFERENCES public.kelas(id) ON DELETE CASCADE,
  judul TEXT NOT NULL CHECK (char_length(judul) >= 3 AND char_length(judul) <= 200),
  konten TEXT NOT NULL CHECK (char_length(konten) >= 10),
  gambar_url TEXT,                                         -- Supporting image
  is_published BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.cerita_kelas IS 'Stories shared by students in class bulletin board';
COMMENT ON COLUMN public.cerita_kelas.author_id IS 'Student or admin who created the story';
COMMENT ON COLUMN public.cerita_kelas.kelas_id IS 'Class where story is published';

-- 4.9 STORY RESPONSES TABLE
-- Comments/responses to class stories
CREATE TABLE public.tanggapan_cerita (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cerita_id BIGINT NOT NULL REFERENCES public.cerita_kelas(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  tanggapan TEXT NOT NULL CHECK (char_length(tanggapan) >= 1 AND char_length(tanggapan) <= 1000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.tanggapan_cerita IS 'Responses/comments to class stories';
COMMENT ON COLUMN public.tanggapan_cerita.cerita_id IS 'Story being responded to';
COMMENT ON COLUMN public.tanggapan_cerita.author_id IS 'User providing the response';

-- 4.10 NOTIFICATIONS TABLE
-- FCM tokens for push notifications
CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  fcm_token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.notifications IS 'FCM tokens for push notifications';

-- =================================================================
-- 5. CREATE INDEXES FOR PERFORMANCE
-- =================================================================

-- Indexes for cerita_kelas
CREATE INDEX idx_cerita_kelas_kelas_id ON public.cerita_kelas(kelas_id);
CREATE INDEX idx_cerita_kelas_author_id ON public.cerita_kelas(author_id);
CREATE INDEX idx_cerita_kelas_created_at ON public.cerita_kelas(created_at DESC);

-- Indexes for tanggapan_cerita
CREATE INDEX idx_tanggapan_cerita_cerita_id ON public.tanggapan_cerita(cerita_id);
CREATE INDEX idx_tanggapan_cerita_author_id ON public.tanggapan_cerita(author_id);
CREATE INDEX idx_tanggapan_cerita_created_at ON public.tanggapan_cerita(created_at DESC);

-- =================================================================
-- 6. CREATE FUNCTIONS
-- =================================================================

-- 6.1 Helper function to get current user's role
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN (
    SELECT role::text FROM public.profiles WHERE id = auth.uid()
  );
END;
$$;

-- 6.2 Function to auto-create user profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', 'siswa');
  RETURN new;
END;
$$;

-- 6.3 Function to get report status counts for dashboard
CREATE OR REPLACE FUNCTION get_report_status_counts()
RETURNS TABLE(status TEXT, total BIGINT) AS $$
BEGIN
  RETURN QUERY
  SELECT r.status::TEXT, COUNT(*) as total
  FROM public.reports r
  GROUP BY r.status;
END;
$$ LANGUAGE plpgsql;

-- 6.4 Function to create new report with evidence
CREATE OR REPLACE FUNCTION create_new_report(
  title TEXT,
  description TEXT,
  is_anonymous BOOLEAN,
  evidence_urls TEXT[]
)
RETURNS void AS $$
DECLARE
  new_report_id BIGINT;
BEGIN
  -- Insert report
  INSERT INTO public.reports (title, description, is_anonymous, reporter_id)
  VALUES (
    title,
    description,
    is_anonymous,
    CASE WHEN is_anonymous THEN NULL ELSE auth.uid() END
  ) RETURNING id INTO new_report_id;

  -- Insert evidence if provided
  IF array_length(evidence_urls, 1) > 0 THEN
    FOR i IN 1..array_length(evidence_urls, 1) LOOP
      INSERT INTO public.evidence (report_id, file_url, file_type)
      VALUES (new_report_id, evidence_urls[i], 'image/jpeg');
    END LOOP;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6.5 Function to auto-update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 6.6 Notification trigger functions
CREATE OR REPLACE FUNCTION notify_new_report_v2()
RETURNS TRIGGER AS $$
DECLARE
  webhook_url text := 'https://hcifdgbwcacjsqzenjq.supabase.co/functions/v1/send-new-report-notification';
  payload jsonb;
  service_key text := 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjaWZkZ2J3Y2FjanNxemVuanEiLCJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU4ODQ1Nzc2LCJleHAiOjIwNzQ0MjE3NzZ9.hJFQYUYCrKjHvG5GqUNlKnDLDfJIGqSWVTOtqIFCHvs';
BEGIN
  payload := jsonb_build_object(
    'type', 'INSERT',
    'table', 'reports',
    'record', to_jsonb(NEW),
    'schema', 'public'
  );

  BEGIN
    PERFORM net.http_post(
      url := webhook_url,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || service_key
      ),
      body := payload
    );
  EXCEPTION 
    WHEN OTHERS THEN
      RAISE NOTICE 'Failed to call webhook: %', SQLERRM;
  END;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION notify_new_reply_v2()
RETURNS TRIGGER AS $$
DECLARE
  webhook_url text := 'https://hcifdgbwcacjsqzenjq.supabase.co/functions/v1/send-reply-notification';
  payload jsonb;
  service_key text := 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjaWZkZ2J3Y2FjanNxemVuanEiLCJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU4ODQ1Nzc2LCJleHAiOjIwNzQ0MjE3NzZ9.hJFQYUYCrKjHvG5GqUNlKnDLDfJIGqSWVTOtqIFCHvs';
BEGIN
  payload := jsonb_build_object(
    'type', 'INSERT',
    'table', 'balasan_laporan',
    'record', to_jsonb(NEW),
    'schema', 'public'
  );

  BEGIN
    PERFORM net.http_post(
      url := webhook_url,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || service_key
      ),
      body := payload
    );
  EXCEPTION 
    WHEN OTHERS THEN
      RAISE NOTICE 'Failed to call webhook: %', SQLERRM;
  END;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =================================================================
-- 7. CREATE TRIGGERS
-- =================================================================

-- 7.1 Auto-create profile on user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 7.2 Auto-update timestamps
CREATE TRIGGER update_cerita_kelas_updated_at 
    BEFORE UPDATE ON public.cerita_kelas 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tanggapan_cerita_updated_at 
    BEFORE UPDATE ON public.tanggapan_cerita 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- 7.3 Notification triggers
CREATE TRIGGER on_report_created
  AFTER INSERT ON public.reports
  FOR EACH ROW
  EXECUTE FUNCTION notify_new_report_v2();

CREATE TRIGGER on_reply_created
  AFTER INSERT ON public.balasan_laporan
  FOR EACH ROW
  EXECUTE FUNCTION notify_new_reply_v2();

-- =================================================================
-- 8. ENABLE ROW LEVEL SECURITY
-- =================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.log_penanganan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.balasan_laporan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.socialization ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cerita_kelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tanggapan_cerita ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kelas ENABLE ROW LEVEL SECURITY;

-- =================================================================
-- 9. CREATE RLS POLICIES
-- =================================================================

-- 9.1 PROFILES POLICIES
CREATE POLICY "Allow authenticated users to view all profiles"
ON public.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow users to update their own profile"
ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

-- 9.2 KELAS POLICIES
CREATE POLICY "Allow authenticated users to view classes"
ON public.kelas FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow TPPK members to manage classes"
ON public.kelas FOR ALL
TO authenticated
USING (get_my_role() = 'tppk')
WITH CHECK (get_my_role() = 'tppk');

-- 9.3 REPORTS POLICIES
CREATE POLICY "Allow users to create reports"
ON public.reports FOR INSERT
TO authenticated
WITH CHECK (reporter_id = auth.uid());

CREATE POLICY "Allow users to view their own reports"
ON public.reports FOR SELECT
TO authenticated
USING (reporter_id = auth.uid());

CREATE POLICY "Allow TPPK members to view all reports"
ON public.reports FOR SELECT TO authenticated USING (get_my_role() = 'tppk');

CREATE POLICY "Allow TPPK members to update all reports"
ON public.reports FOR UPDATE TO authenticated USING (get_my_role() = 'tppk');

CREATE POLICY "Allow teachers to view reports from their class"
ON public.reports FOR SELECT
TO authenticated
USING (
  get_my_role() = 'guru'
  AND is_anonymous = false
  AND (
    (SELECT p.kelas_id FROM public.profiles p WHERE p.id = reports.reporter_id) 
    = 
    (SELECT k.id FROM public.kelas k WHERE k.wali_kelas_id = auth.uid())
  )
);

-- 9.4 EVIDENCE POLICIES
CREATE POLICY "Allow authenticated users to insert evidence"
ON public.evidence FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Allow users to view evidence for their reports or if TPPK"
ON public.evidence FOR SELECT TO authenticated USING (
  (get_my_role() = 'tppk') OR
  (EXISTS (
    SELECT 1 FROM public.reports
    WHERE reports.id = evidence.report_id AND reports.reporter_id = auth.uid()
  ))
);

CREATE POLICY "Allow TPPK members to delete evidence"
ON public.evidence FOR DELETE TO authenticated USING (get_my_role() = 'tppk');

-- 9.5 LOG PENANGANAN POLICIES
CREATE POLICY "Allow TPPK to view handling logs"
ON public.log_penanganan FOR SELECT
TO authenticated
USING (get_my_role() = 'tppk');

CREATE POLICY "Allow TPPK to insert handling logs"
ON public.log_penanganan FOR INSERT
TO authenticated
WITH CHECK (get_my_role() = 'tppk');

-- 9.6 BALASAN LAPORAN POLICIES
CREATE POLICY "Allow TPPK to create replies"
ON public.balasan_laporan FOR INSERT
TO authenticated
WITH CHECK (get_my_role() = 'tppk');

CREATE POLICY "Allow reporter to view their replies"
ON public.balasan_laporan FOR SELECT
TO authenticated
USING (
  (SELECT reporter_id FROM public.reports WHERE id = report_id) = auth.uid()
);

CREATE POLICY "Allow TPPK to view all replies"
ON public.balasan_laporan FOR SELECT
TO authenticated
USING (get_my_role() = 'tppk');

-- 9.7 SOCIALIZATION POLICIES
CREATE POLICY "Allow authenticated users to view socialization content"
ON public.socialization FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow TPPK members to create socialization content"
ON public.socialization FOR INSERT TO authenticated WITH CHECK (get_my_role() = 'tppk');

CREATE POLICY "Allow TPPK members to update socialization content"
ON public.socialization FOR UPDATE TO authenticated USING (get_my_role() = 'tppk');

CREATE POLICY "Allow TPPK members to delete socialization content"
ON public.socialization FOR DELETE TO authenticated USING (get_my_role() = 'tppk');

-- 9.8 CERITA KELAS POLICIES
CREATE POLICY "Users can view stories in their class" ON public.cerita_kelas
    FOR SELECT USING (
        (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        OR
        (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
            AND kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
        )
        OR
        (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'guru'
            AND kelas_id IN (SELECT id FROM public.kelas WHERE wali_kelas_id = auth.uid())
        )
    );

CREATE POLICY "Students and admins can create stories" ON public.cerita_kelas
    FOR INSERT WITH CHECK (
        author_id = auth.uid()
        AND (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
            OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        )
        AND (
            (
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
                AND kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
            )
            OR
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        )
    );

CREATE POLICY "Authors and admins can update their stories" ON public.cerita_kelas
    FOR UPDATE USING (
        author_id = auth.uid()
        OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
    );

CREATE POLICY "Authors and admins can delete their stories" ON public.cerita_kelas
    FOR DELETE USING (
        author_id = auth.uid()
        OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
    );

-- 9.9 TANGGAPAN CERITA POLICIES
CREATE POLICY "Users can view responses if they can view the story" ON public.tanggapan_cerita
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.cerita_kelas 
            WHERE id = cerita_id
            AND (
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
                OR
                (
                    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
                    AND kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
                )
                OR
                (
                    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'guru'
                    AND kelas_id IN (SELECT id FROM public.kelas WHERE wali_kelas_id = auth.uid())
                )
            )
        )
    );

CREATE POLICY "Users can create responses if they can view the story" ON public.tanggapan_cerita
    FOR INSERT WITH CHECK (
        author_id = auth.uid()
        AND EXISTS (
            SELECT 1 FROM public.cerita_kelas 
            WHERE id = cerita_id
            AND (
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
                OR
                (
                    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
                    AND kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
                )
                OR
                (
                    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'guru'
                    AND kelas_id IN (SELECT id FROM public.kelas WHERE wali_kelas_id = auth.uid())
                )
            )
        )
    );

CREATE POLICY "Authors and admins can update their responses" ON public.tanggapan_cerita
    FOR UPDATE USING (
        author_id = auth.uid()
        OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
    );

CREATE POLICY "Authors and admins can delete their responses" ON public.tanggapan_cerita
    FOR DELETE USING (
        author_id = auth.uid()
        OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
    );

-- 9.10 NOTIFICATIONS POLICIES
CREATE POLICY "Allow users to view their own notification tokens"
ON public.notifications FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Allow users to create their own notification tokens"
ON public.notifications FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to delete their own notification tokens"
ON public.notifications FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- =================================================================
-- 10. STORAGE POLICIES (for cerita-images bucket)
-- =================================================================

-- Students and admins can upload story images
CREATE POLICY "Students and admins can upload story images" ON storage.objects
    FOR INSERT WITH CHECK (
        bucket_id = 'cerita-images'
        AND (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
            OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        )
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

-- Users can view story images in their class
CREATE POLICY "Users can view story images in their class" ON storage.objects
    FOR SELECT USING (
        bucket_id = 'cerita-images'
        AND (
            (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
            OR
            (
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'siswa'
                AND EXISTS (
                    SELECT 1 FROM public.cerita_kelas ck
                    WHERE ck.gambar_url LIKE '%' || name || '%'
                    AND ck.kelas_id = (SELECT kelas_id FROM public.profiles WHERE id = auth.uid())
                )
            )
            OR
            (
                (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'guru'
                AND EXISTS (
                    SELECT 1 FROM public.cerita_kelas ck
                    JOIN public.kelas k ON ck.kelas_id = k.id
                    WHERE ck.gambar_url LIKE '%' || name || '%'
                    AND k.wali_kelas_id = auth.uid()
                )
            )
        )
    );

-- Authors and admins can update their story images
CREATE POLICY "Authors and admins can update their story images" ON storage.objects
    FOR UPDATE USING (
        bucket_id = 'cerita-images'
        AND (
            auth.uid()::text = (storage.foldername(name))[1]
            OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        )
    );

-- Authors and admins can delete their story images
CREATE POLICY "Authors and admins can delete their story images" ON storage.objects
    FOR DELETE USING (
        bucket_id = 'cerita-images'
        AND (
            auth.uid()::text = (storage.foldername(name))[1]
            OR (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk'
        )
    );

-- =================================================================
-- 11. SEED DATA
-- =================================================================

-- Insert initial class data
INSERT INTO public.kelas (tingkat, jurusan) VALUES
-- Grade 1
(1, 'A'), (1, 'B'), (1, 'C'), (1, 'D'),
-- Grade 2
(2, 'A'), (2, 'B'), (2, 'C'), (2, 'D'),
-- Grade 3
(3, 'A'), (3, 'B'), (3, 'C'), (3, 'D'),
-- Grade 4
(4, 'A'), (4, 'B'), (4, 'C'), (4, 'D'),
-- Grade 5
(5, 'A'), (5, 'B'), (5, 'C'), (5, 'D'), (5, 'E'),
-- Grade 6
(6, 'A'), (6, 'B'), (6, 'C'), (6, 'D'), (6, 'E');

-- =================================================================
-- 12. CONFIGURATION
-- =================================================================

-- Set service role key for database triggers
-- NOTE: Replace with actual service role key from Supabase Dashboard
ALTER DATABASE postgres SET "app.settings.service_role_key" TO 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjaWZkZ2J3Y2FjanNxemVuanEiLCJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNzU4ODQ1Nzc2LCJleHAiOjIwNzQ0MjE3NzZ9.YOUR_ACTUAL_SERVICE_ROLE_KEY_HERE';

-- =================================================================
-- INITIALIZATION COMPLETE
-- =================================================================

-- Verify extensions are enabled
SELECT 'pg_net extension enabled' as status WHERE EXISTS (
  SELECT 1 FROM pg_extension WHERE extname = 'pg_net'
);

-- Display summary of created objects
SELECT 
  'Database initialization completed successfully!' as message,
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public') as tables_created,
  (SELECT COUNT(*) FROM information_schema.routines WHERE routine_schema = 'public') as functions_created;

-- =================================================================
-- NOTES FOR DEPLOYMENT:
-- 
-- 1. Replace the service_role_key with your actual Supabase service role key
-- 2. Update webhook URLs in notification functions if using different Supabase project
-- 3. Create the 'cerita-images' storage bucket in Supabase Dashboard
-- 4. Test all RLS policies with different user roles
-- 5. Consider creating indexes on frequently queried columns
-- 
-- SECURITY CONSIDERATIONS:
-- - All tables have RLS enabled
-- - Semi-anonymous reports: reporter_id is stored but name hidden in UI when is_anonymous = true
-- - Teachers can only see non-anonymous reports from their own class
-- - Students can only interact with content from their own class
-- - Admins (TPPK) have full access to manage all content
-- 
-- =================================================================
