-- Migration: Add user deletion logging table
-- Track all user deletions for audit purposes

-- 1. Create table for logging user deletions
CREATE TABLE public.user_deletion_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deleted_user_id uuid NOT NULL,                          -- ID of deleted user
  deleted_user_name text NOT NULL,                        -- Name of deleted user
  deleted_user_email text,                                -- Email of deleted user (if available)
  deleted_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL, -- Admin who deleted
  deletion_reason text NOT NULL,                          -- Reason for deletion
  deleted_at timestamptz NOT NULL DEFAULT now()           -- When deletion occurred
);

-- 2. Add comments for documentation
COMMENT ON TABLE public.user_deletion_log IS 'Audit log for user data deletions';
COMMENT ON COLUMN public.user_deletion_log.deleted_user_id IS 'UUID of the deleted user';
COMMENT ON COLUMN public.user_deletion_log.deleted_user_name IS 'Full name of deleted user for reference';
COMMENT ON COLUMN public.user_deletion_log.deleted_by IS 'Admin who performed the deletion';
COMMENT ON COLUMN public.user_deletion_log.deletion_reason IS 'Reason provided for deletion';

-- 3. Enable RLS
ALTER TABLE public.user_deletion_log ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies - only TPPK can view deletion logs
CREATE POLICY "Only TPPK can view deletion logs"
ON public.user_deletion_log FOR SELECT TO authenticated
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk');

CREATE POLICY "Only TPPK can insert deletion logs"
ON public.user_deletion_log FOR INSERT TO authenticated
WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'tppk');

-- 5. Create index for performance
CREATE INDEX idx_user_deletion_log_deleted_at ON public.user_deletion_log(deleted_at DESC);
CREATE INDEX idx_user_deletion_log_deleted_by ON public.user_deletion_log(deleted_by);

-- 6. Create RPC function to delete user completely
CREATE OR REPLACE FUNCTION public.delete_user_completely(
  user_id_to_delete uuid,
  deletion_reason text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Only allow TPPK to delete users
  IF (SELECT role FROM public.profiles WHERE id = auth.uid()) != 'tppk' THEN
    RAISE EXCEPTION 'Only TPPK can delete users';
  END IF;
  
  -- Prevent self-deletion
  IF user_id_to_delete = auth.uid() THEN
    RAISE EXCEPTION 'Cannot delete your own account';
  END IF;
  
  -- Log the deletion first
  INSERT INTO public.user_deletion_log (
    deleted_user_id,
    deleted_user_name,
    deleted_by,
    deletion_reason
  )
  SELECT 
    user_id_to_delete,
    p.full_name,
    auth.uid(),
    deletion_reason
  FROM public.profiles p
  WHERE p.id = user_id_to_delete;
  
  -- Delete from profiles (will cascade to related data)
  DELETE FROM public.profiles WHERE id = user_id_to_delete;
  
  -- Delete from auth.users (requires service_role)
  DELETE FROM auth.users WHERE id = user_id_to_delete;
END;
$$;
